### PR TITLE
Alternate tiny planet block recipe

### PR DESCRIPTION
**Pull request by GDCloudstrike**
Adds an alternate recipe for the tiny planet block for further use in recipes for the nei planet blocks (for eye of harmony recipe selection)

### CODE REVIEW

**Review by POPlol333 — APPROVED** [review]

**Review by glowredman — CHANGES_REQUESTED** [review]
Changes like this should be done in Botanic Horizons

**Comment by Dream-Master** [comment]
@glowredman isnt this botanic horizons?

**Review by glowredman — APPROVED** [review]
Oh you're right, sorry. Maybe I shouldn't review PRs right after waking up...

**Comment by combusterf** [comment]
Please PLEASE do not use magic numbers like that, now it's impossible to read or decode what this recipe is and does. Pretty much every GT item has oredict.

**Pull request merged**
