### PR TITLE
Revert "Alternate tiny planet block recipe"

### PR DESCRIPTION
**Pull request by combusterf**
Reverts GTNewHorizons/Botanic-horizons#18

Serious code quality regressions that need to be fixed:
- Uses undocumented magic numbers in new recipes
- Breaks every layout feature meant to make recipe reading easier.
- Forces said inappropriate code layout as the quality standard.

### CODE REVIEW

**Comment by boubou19** [comment]
update the buildscript again and it's merged

**Review by Connor-Colenso — CHANGES_REQUESTED** [review]
This will fully revert necessary EOH recipes, so a proper fix rather than a full revert seems eminently necessary before a quick merge happens.

**Comment by combusterf** [comment]
The fact that I can't even tell what recipes there should be means that it's unmaintainable, and your request unreasonable.

**Comment by Connor-Colenso** [comment]
My request to discuss rather than just revert instantly is unreasonable? Please discuss this in #mod-dev further so we can understand your issue.

**Comment by combusterf** [comment]
I'm sorry I've lost my patience with you a long time ago. If you really need it, you are the one who knows how to fix it, I do not, and I can't be assed to find out. My problem is 4000 lines bigger than your four.

**Comment by mitchej123** [comment]
> My request to discuss rather than just revert instantly is unreasonable? Please discuss this in #mod-dev further so we can understand your issue.

revert first, discuss, resubmit PR with proper standards upheld.  Done.

**Comment by riking** [comment]
Coming here from the changelog: Wow that patch is impossible to read. So many entirely unrelated formatting changes.

**Pull request merged**
